name: Convert Markdown to Discord

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: MarkdownToDiscord
        uses: LittleBigRefresh/MarkdownToDiscord@v1.1.3
        with:
          discordToken: ${{ secrets.DISCORD_TOKEN }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          markdownDirectory: "discord"